### ISSUE TITLE
Error starting docker container

### ISSUE THREAD

**Issue by tasehli** [criteo/cassandra_exporter#10]
Hello,
When starting the docker container I get the following error: Error: Could not find or load main class Xmx

**Comment by deimosfr** [comment]
Hi,

Can you please give more precision on how you're running it (command line).

Thanks

**Comment by erebe** [comment]
Fixed by https://github.com/criteo/cassandra_exporter/commit/fa3e143f5acc19ab5d9315e517e6610cd3c6b895, sorry about that.

You can either re-pull the docker image to get the fix or start your actual image with `docker -e JVM_OPTIONS=-Xmx1024m xxxx` to workaround the issue

**Comment by tasehli** [comment]
Hi, thank you for the fix  that actually solved the problem.
I am closing the issue.
