### ISSUE TITLE
Support listen on specific address

### ISSUE THREAD

**Issue by soloradish** [criteo/cassandra_exporter#12]
There is no way to configure cassandra_exporter listen on specific address in current version.

I use ansible control my cluster running on aws, I want exporter listen on EC2 instance's secondary private ip address to simplify my ansible settings.

Thank you for this great project.

**Comment by erebe** [comment]
You can try this release https://github.com/criteo/cassandra_exporter/releases/tag/1.0.2
and you will be able to add in your config file a `listenAddress: x.x.x.x`

Let me know if it is working for you so I can make the relase permanent

**Comment by erebe** [comment]
Available in 2.0.0 https://github.com/criteo/cassandra_exporter/releases/tag/2.0.0
