### ISSUE TITLE
Create simple endpoint for health checking

### ISSUE THREAD

**Issue by eyalzek** [criteo/cassandra_exporter#17]
Health checking `/` or `/metrics` doesn't like a very good idea, especially when dealing with large cluster that contain many keyspaces and data.

**Comment by deimosfr** [comment]
Can you provide more information on what is the problem you would like to solve? Thanks

**Comment by erebe** [comment]
You can't have better healthcheck than the exporter actually exporting metrics.

**Comment by eyalzek** [comment]
My use case is defining a `readinessProbe`/`livenessProbe` when running this inside kubernetes (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request). Besides the prometheus scraping, it seems to me that hitting the `/metrics` endpoint every 10 seconds (the default `periodSeconds`) can create unwanted load on the container, or run redundant scrapes.

**Comment by deimosfr** [comment]
Here is how I'm using it: https://github.com/MySocialApp/kubernetes-helm-chart-cassandra/blob/master/kubernetes/templates/statefulset.yaml#L162 and it works pretty well. What you'd like is a /health right ?

**Comment by eyalzek** [comment]
Yes, that's definitely a way to do it, but a simple `/health` would be in my opinion better, since it could be ping'd on a shorter interval without interference to the actual exporter. It's nice to have :)

**Comment by erebe** [comment]
What would the /health check ?

>  or run redundant scrapes.
That will not be the case, the scrapes frequency is bounded by the value of your config file.

**Comment by deimosfr** [comment]
/health should just say the exporter is working properly (print "ok" if everything is fine)

**Comment by erebe** [comment]
Won't do it as : 

1. Adding a new endpoint will be complicated, as for now the http endpoint is embeded in the prometheus library and I don't have access to it at the level of the app
2. I feel the /health endpoint is redundant (but I may be biased due to the point 1) as you can do HEAD request or use the filtering feature to get a simple /health

As always, PR are welcome :)
