### ISSUE TITLE
Separated statistics per node

### ISSUE THREAD

**Issue by phamtrinli** [criteo/cassandra_exporter#18]
Hi,

thanks for your efforts of putting this together! Is there a way to get statistics per node in the cluster as well? Sometimes single nodes misbehave where a dashboard helps to quickly identify a faulty node.

Kind regards,
Christian

**Comment by deimosfr** [comment]
If you're using the given grafana dashboard, simply edit the wished graph and you'll see 1 unused metric. Hide the current one and unhide the unused one, you'll see it per node :)

**Comment by phamtrinli** [comment]
Great thats what I was looking for :-)
