### ISSUE TITLE
entrypoint overrride

### ISSUE THREAD

**Issue by spepe91** [criteo/cassandra_exporter#28]
Greetings,

I'm having a small implementation issue with this exporter.

I have created my own dockerfile which is using this image "criteord/cassandra_exporter". The dockerfile will overwrite the entrypoint of the exporter image, with a script that will put the exporter on hold and will wait until cassandra is up and the port is listening. After the DB is up, the CMD's of the exporter will launch, via the script -this was the procedure that worked on other DB's with images that had a simple /bin/exporter entrypoint with and/or connection string(that connected to a DB).

I couldn't make it with this exporter and would like to know if you could offer some suggestion on how to implement it via the method above or other methods that work.

Thank you in advance.

**Comment by erebe** [comment]
Not sure to understand correctly, let me know if I missed your question.

You can call the entrypoint `CMD ["/sbin/dumb-init", "/bin/bash", "/run.sh"]` yourself in your dockerfile.

But even if the DB is not ready/there is not port to connect to, the exporterthrow an exception and try to reconnect 1 sec later.
So if you want to change the entrypoint just to wait for cassandra to be ready, there is no need as the exporter will retry to connect every 1 second.

**Comment by spepe91** [comment]
Thank you for your prompt answer Erebe.

I forgot to mention that the exporter will be used in openshift -the DB/ready script is for the pod not to crash(due to the readiness/liveness probe).

Copied the dockerfile folder from this repo, modified the config file, built the image and pushed it into a registry, ran the pod, but now it throws this error "Error: Unable to access jarfile /opt/cassandra_exporter/cassandra_exporter.jar"

Probably this is not very clear.

**Comment by erebe** [comment]
Can you post me your docker file ?

**Comment by spepe91** [comment]
Dockerfile is simple, it uses the exporter cassandra docker image from docker hub, installs netstat, so it can check if the port is listening, adds the script, assigns permission to him and overrides the CMD of the cassandra exporter.
After the script checks that the DB is up and the port is listening, some binaries will be executed.

1.For example, the mariaDB exporter and others exporters use similar dockerfiles:
https://hub.docker.com/r/prom/mysqld-exporter/~/dockerfile/

2.prom/mysqld-exporter image will be used in my docker file, script will be applied and after the script loop check is finished, it will execute this line: "/bin/mysqld_exporter". And that's it.
I'm not really an experienced guy, so I'm open to any solution.

-------------------
FROM criteord/cassandra_exporter

RUN apt-get update \
      && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        net-tools \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

ADD check.sh /

RUN chmod +x /ready.sh

ENTRYPOINT [ "/bin/sh", "/ready.sh" ]

**Comment by erebe** [comment]
The image criteord/cassandra_exporter:2.0.1 should do what you want (https://github.com/criteo/cassandra_exporter/commit/0a00d61cf286a75bfc9f3e136275f3ff0778f933)

Let me know if it no the case

**Comment by spepe91** [comment]
Thank you for taking time to update the image

I have tested "criteord/cassandra_exporter:2.0.1" in openshift, used it as it is, without any modifications, but it gives me the error below. Can the image be used alone without any other configuration files or scripts?

![image](https://user-images.githubusercontent.com/43374270/45740820-c9692a80-bbfe-11e8-9851-a576fec8e0b5.png)

**Comment by erebe** [comment]
Yep the image could be used alone. On your machine you can do a `sudo docker run --rm -ti --net=host  criteord/cassandra_exporter:2.0.1` and it will start. If you do in an other shell `sudo docker run --rm -ti --net=host  cassandra` the exporter will start (and crash as jmx is not enabled in the docker image)

Seems to be an issue with openshift, I can't help you on that sadly :'(

**Comment by spepe91** [comment]
Yep, if the containers are started as you mentioned above, it works perfect.
Gotta figure out how openshift treats the exporter files and directories, it's clearly something from openshift, probably some permission issues.

Thanks for helping out! :D
