### ISSUE TITLE
Cant retrieve Datacenter name ERROR

### ISSUE THREAD

**Issue by bamartos** [criteo/cassandra_exporter#34]
Hi,

When I am trying to run the exporter (v2.0.3) I receive: 
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot retrieve the datacenter name information for the node
javax.management.AttributeNotFoundException: No such attribute: Datacenter

In the config.yml file we tried to blacklist the node - org:apache:cassandra:db:.* but it didnt help.

It seems that the error is related with the code on JmxScraper.java:373. We tried to use and older (v1.0.1) which is not parsing the Datacenter name and it worked fine. 

We are using Cassandra 3.0.6,

Cheers

**Comment by erebe** [comment]
Hello,
Thanks for reporting. It should be good with the release 2.1.0

Let me know if it is ok or not for you

**Comment by bamartos** [comment]
Yes, it works now, 

Thanks for your super fast response, you can close the issue.

Cheers
