### ISSUE TITLE
Expose metrics in / instead of /metrics

### ISSUE THREAD

**Issue by kaisermario** [criteo/cassandra_exporter#38]
Hi all, 

I have a short question. 
Is it possible by passing config to expose the metrics at root path / instead of /metrics?

Thanks a lot!

Cheers

**Comment by erebe** [comment]
Hello @kaisermario,

You can already do it :) Just try to open in your browser the / and  you should find the metrics

**Comment by kaisermario** [comment]
I know that there is a link to get the metrics. 
And that looks like this: 

**Node Exporter**
Link to Metrics

Is it possible to expose the metrics directly without this "landing page" ?

**Comment by erebe** [comment]
I am confused now...
If you are talking about the exporter itself (the java program), it will expose the metrics on any pages you request so / and /metrics.
You can try starting the program on your machine and do `curl localhost:8080/` to see by yourself.

If you are talking about something else than the java program I don't know.

**Comment by kaisermario** [comment]
@erebe sorry for confusion. It works perfectly!
