### ISSUE TITLE
Logs are parsed to stderr instead of stdout

### ISSUE THREAD

**Issue by larstonne** [criteo/cassandra_exporter#47]
For example scrape logs are parsed to stderr. It would be nice to have only errors appear in stderr cause it makes monitoring alot simpler ;D

**Comment by erebe** [comment]
You can change the logging ouput by starting cassandra_exporter with this parameter
-Dorg.slf4j.simpleLogger.logFile 
The output target which can be the path to a file, or the special values "System.out" and "System.err". Default is "System.err".
