### ISSUE TITLE
Grafana 6.0 dashboard is empty

### ISSUE THREAD

**Issue by therb1** [criteo/cassandra_exporter#49]
Hi!
Is my grafana gone crazy or is this dashboard not working in version 6.0.1?
https://github.com/criteo/cassandra_exporter/blob/grafana/grafana/cassandra_default.json

**Comment by erebe** [comment]
Hello,
I don't have grafana 6.x under hand so right now I can't tell
I will try to test it out when I have a bit of time and will let you know

**Comment by therb1** [comment]
**Workaround.**

Change **datasource** variable in **cassandra_default.json**.
From:

> "datasource": null

To:

> "datasource": "youre prometheus datasource name"

Like:

> "datasource": "Prometheus"

**Comment by therb1** [comment]
In grafana 6.2.2 you must use placeholder like

> "datasource": "$datasource"

I made this conclusion on the basis of a dashboard that I exported from grafana and marked "Export for sharing externally"

@erebe What do you think about this?

**Comment by therb1** [comment]
solved!
