### ISSUE TITLE
[Help needed] Minimal metrics setup to monitor node health

### ISSUE THREAD

**Issue by Blasterdick** [criteo/cassandra_exporter#55]
I'm very new to Cassandra and need to healthcheck a cluster of 5 Cassandra nodes with ~1000 of keyspaces created.

With the default setup, I'm getting a huge number of metrics in my Prometheus, which makes it impossible to query for a time range of more than 1 hour, then it gets killed by OOM. And all those metrics aren't informative to me.

So for the sake of future users, who faced the same problem, I wonder is there a minimal config for the metrics to scrape so average administrator could take a look at and see if there is (or gonna be) something wrong with Cassandra?

Thanks in advance for any kind of help and excuse me for my barbarian English.

**Comment by erebe** [comment]
Hello,

I think you are hitting an edge case of the use case of Cassandra. I don't even think it is recommended to have that much keyspaces for that little number of machines.

You will have an hard time to scale your metrics system has it is the number of keyspace/table that makes the cardinality of metrics exposed by Cassandra to increase linearly.

That being said, it is not helpful to you. If it was me and with this number of keyspaces, I would keep only metrics regarding read/write/range latencies per table and let the system administrator makes the effort to drill down by using visualvm on the cluster.
- org:apache:cassandra:metrics:table:$Keyspace:$Table:{read,write,range}latency:$Percentile

But be aware that troubleshooting when you have an issue will be painful :x 

Let me know if this is not enough
