### ISSUE TITLE
Streaming related metrics are missing

### ISSUE THREAD

**Issue by sandeepnethi** [criteo/cassandra_exporter#56]
Hi,

I'm using cassandra_exporter-2.2.1 pre-built library for exporting cassandra metrics and found that streaming related metrics are missing. 

Do you guys aware of this problem or I'm I missing something here?

Thanks.

**Comment by erebe** [comment]
Hello,

From my experience, those metrics appears in Cassandra only after that you have streamed something. If you reboot the node or haven't streamed anything, the metric is not present.

Not sure if this is a expected behavior for Cassandra, but that's what I have seen

**Comment by sandeepnethi** [comment]
@erebe You're correct!. 

We can see this metric only when it gets triggered. 

Thanks for the quick reply. appreciate your time. 

Cheers.
