### ISSUE TITLE
Nodes up/down status

### ISSUE THREAD

**Issue by hadarizi** [criteo/cassandra_exporter#57]
Hi,
I couldn't find any metric which gives the node status.
The closest metric is using "up" but this only indicates if the exporter is up/down.

**Comment by erebe** [comment]
Hello,
There is no good way to monitor if a node is available or not trough jmx/cassandra exporter. As you may be able to retrieve metrics from cassandra but the node may still be unresponsive to request.

To measure avaibility of our cluster we use https://github.com/criteo/casspoke, which is an external probe that send request to every node on the system keyspace. So far it works well for us and is able to detect when a node is un-healthy
