### ISSUE TITLE
Map Cassandra metrics with non-numeric value into metric name or label

### ISSUE THREAD

**Issue by mimarpe** [criteo/cassandra_exporter#65]
Hi,

I'm particularly interested in the metric:

> org.aparche.cassandra.metrics.compaction.pendingtasksbytablename

The value is a map like _{columnfamily1:number, columnfamily2:number,...}_.

Is there a way to tell cassandra-exporter to map this metric into something compatible with prometheus, like using prometheus labels, or changing the metric name?
E.g.:
cassandra_stats{name="org.aparche.cassandra.metrics.compaction.pendingtasksbytablename:<name_of_cf>"}

That way we can store in Prometheus the pending compactions with column family granularity and detect if a particular CF is suffering specially from compaction.

Thanks, regards,
    Miguel

**Comment by geobeau** [comment]
Hello, sorry for the delay, opened a PR with the new metric

**Comment by mimarpe** [comment]
Top, je vais le tester des que dispo, ou prendre ton fork.
Merci!

**Comment by erebe** [comment]
Closing has it has been released
