### ISSUE TITLE
How can i start exporter?

### ISSUE THREAD

**Issue by tabbi** [criteo/cassandra_exporter#70]
**to start the application
    java -jar cassandra_exporter.jar config.yml**

git clone https://github.com/criteo/cassandra_exporter.git
cd cassandra && java -jar cassandra_exporter.jar config.ym 
java -jar cassandra_exporter.jar config.ym
Error: Unable to access jarfile cassandra_exporter.jar

find / -name "cassandra_exporter.jar" 2> /devnull
and the result is nothing
how can i start the exporter?

**Comment by geobeau** [comment]
You have three way to do it:
- You need to build it from source with `gradle build` (you will need to install gradle)
- You can download jar from the last release [here](https://github.com/criteo/cassandra_exporter/releases)
- You can start it with the docker image provided `docker pull criteord/cassandra_exporter:latest`

**Comment by yakirgb** [comment]
I'm using systemd to start cassandra_exporter.
systemd file:
```
[Unit]
Description=Prometheus Cassandra Exporter
After=cassandra.service network.target

[Service]
Type=simple
User=cassandra
Group=cassandra
ExecStart=/etc/cassandra/conf/prometheus/cassandra_exporter.sh
Restart=always

[Install]
WantedBy=multi-user.target
```

Script of ExecStart: 
```
#!/bin/bash
java -Dorg.slf4j.simpleLogger.logFile=/var/log/cassandra/cassandra_exporter.log -jar /usr/share/prometheus/cassandra_exporter-2.3.2.jar /etc/cassandra/conf/prometheus/cassandra_exporter_config.yml
```
