### ISSUE TITLE
Prometheus way to filtering metrics

### ISSUE THREAD

**Issue by ChaitanyaManthena** [criteo/cassandra_exporter#78]
Hi Team,

I am able to run the cassandra_exporter and able to see the metrics in UI. Usually we write the rules in exporter.yml to filter out the metrics, where how can we pass the rules yml file to filter out. 

Or can we directly import the metrics in grafana and filter out as we have more number of cassandra servers checking on this.

**Comment by geobeau** [comment]
You can check the `blacklist` part in https://github.com/criteo/cassandra_exporter/blob/master/config.yml
Or you can use metric_relabel_config in your prometheus configuration to keep only the metrics you want.

I'm not sure I understand the part about importing in Grafana. Grafana typically reads from a datasource (a Prometheus instance for example). Maybe you mean Grafana Cloud ?

**Comment by ChaitanyaManthena** [comment]
@geobeau 
I am able to get the details by using consul auto discovery method. Want list the the metrics in a meaning full way to pass in Grafan (for viewing). We usually used the below rules as mentioned below to get the specific metrics, i tried using in config.yml while running the jar but didnt help. Is there a way to pass this rules.yml to filtering.

  rules:
    - pattern: org.apache.cassandra.metrics&amp;lt;type=(Connection|Streaming), scope=(\S*), name=(\S*)&amp;gt;&amp;lt;&amp;gt;(Count|Value)
      name: cassandra_$1_$3
      labels:
        address: "$2"

**Comment by ChaitanyaManthena** [comment]
@geobeau 
want to elaborate more, from the metrics i am getting as below and want to eliminate those from name to get more meaningful alert. 

cassandra_stats{address="ip:0",dc="dc",env="test",instance="host",job="cassandra-v2",name="java:lang:classloading:loadedclasscount"}

org:apache:cassandra:internal:
java:lang:classloading:
org:apache:cassandra:metrics:

**Comment by geobeau** [comment]
To do that you will need use `metric_relabel_config ` inside your prometheus configuration. Probably a regex that keep only the part that you want. You can check https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs
