### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by hleb-albau** [criteo/cassandra_exporter#8]
Hi, thanks for the project!

Do you have grafana dashboard for cassandra metrics?

**Comment by akhan4u** [comment]
Hi @deimosfr ,

How can i add the instance, cluster related details in the metrics. I also see your dashboard is specific to cassandra in kubernetes... 

Can you please guide.

**Comment by deimosfr** [comment]
Hi,

This version is a draft for the moment, that's why I didn't replied with a link 😜. 

You need to configure the template with your infos to make it works.

**Comment by soloradish** [comment]
Need dashboard +1

**Comment by deimosfr** [comment]
Hi,

Here is a beta version working with Kubernetes https://grafana.com/dashboards/6258.

Another one without Kubernetes will shortly come.

Thanks for your patience

**Comment by deimosfr** [comment]
Hi,

I'm closing the issue as we provided dashboards. More info here: https://github.com/criteo/cassandra_exporter/tree/grafana/grafana

Pierre
