### ISSUE TITLE
How this jar scrape metrics from cassandra

### ISSUE THREAD

**Issue by rjshrjndrn** [criteo/cassandra_exporter#85]
I couldn't find any documentation on how this exporter scrape the metrics from Cassandra?
I meant do we have to enable some JMX metrics or plain vanilla Cassandra installation will do?
One more clarification is, what is [this](https://github.com/criteo/cassandra_exporter/blob/6ac8ac4a242bc40d2acf91b7ca681dc977e14c9f/config.yml#L1) host entry in config file?
does that mean Cassandra has to expose some metrics over there ? or this exporter will expose metrics in that port ? in that case 5th and 6h line (listenaddress and port) are invalid.
Sorry for the simple questions. but trying to figure out how this works.

**Comment by erebe** [comment]
You need to run an exporter per cassandra node.
After that you will find your metrics by looking at the port you configured  with you web-browser.
i.e: 
```
host: localhost:7199
```
in your browser
```
firefox http://localhost:7199/metrics
```

Regarding how to scrape the metrics with prometheus, I will let you look at the doc of prometheus for that.

**Comment by rjshrjndrn** [comment]
What I asked was how this application will talk to cassandra for the metrics. As I can see vanilla installation of cassandra has doesn't have anything listening on port `:7111`

**Comment by erebe** [comment]
It uses JMX, by default on port 7199 on cassandra and in this exporter.
