### ISSUE TITLE
Exporter required on every cassandra node?

### ISSUE THREAD

**Issue by a-nldisr** [criteo/cassandra_exporter#91]
After bringing up a few of these exporters on a set of cassandra nodes it seems to me that all the metrics are there. Is it required to have an exporter on every Cassandra node to get a full view?

Sorry for the question I couldn't find an channel or place where i could ask for details.

**Comment by erebe** [comment]
Hello,
Yes indeed you need to deploy 1 exporter per cassandra node in order to get the full view of the cluster.

**Comment by a-nldisr** [comment]
Thanks!
