### ISSUE TITLE
ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for com.criteo.nosql.cassandra.exporter.JmxScraper$MBeanInfo@35b4d582Value javax.management.AttributeNotFoundException: No such attribute: Value

### ISSUE THREAD

**Issue by sandirirajkumar** [criteo/cassandra_exporter#93]
Hi ,

I am using cassandra version 2.1.14 and java version below:
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Cassandra exporter jar version:
cassandra_exporter-2.2.1-all.jar

Error in cassandra_exporter log:

ERROR com.criteo.nosql.cassandra.exporter.JmxScraper - Cannot get value for com.criteo.nosql.cassandra.exporter.JmxScraper$MBeanInfo@35b4d582Value
javax.management.AttributeNotFoundException: No such attribute: Value

Please do the needful to fix this issue.

Thanks
Raj

**Comment by erebe** [comment]
Hello,

The exporter does not support cassandra 2.1.X version as they have been EOL for some times now.
You can use 1.x version of the exporter if you want support for it. But you will just get raw metrics.
