### ISSUE TITLE
Grafana v7.3.7 Integration

### ISSUE THREAD

**Issue by fhopp** [criteo/cassandra_exporter#97]
Hey there, 

I am trying to use your exporter to monitor a 6 node cassandra cluster. 
For starters, I downloaded the `cassandra_exporter-2.3.5.jar` and config.yml and changed listening port to 8082- this port is open and I can collect metrics at the dedicated URL, e.g.:

```
# HELP cassandra_stats node stats
# TYPE cassandra_stats gauge
cassandra_stats{cluster="MNL Cassandra 21",datacenter="datacenter1",keyspace="",table="",name="org:apache:cassandra:metrics:indexcolumnfamily:icore2020:gkg_record_by_day:gkg_record_by_day_source_idx:bloomfilterfalseratio:value",} 0.0
cassandra_stats{cluster="MNL Cassandra 21",datacenter="datacenter1",keyspace="",table="",name="org:apache:cassandra:metrics:indextable:icore2020:gkg_record_by_year:gkg_record_by_year_named_entities_idx:rangelatency:oneminuterate",} 0.0
```

However, when I go to the Grafana interface and try to add the datasource with URL `http://localhost:8082` and click 'Save & Test', the blue testing badge appears but it does not seem to actually get fully added. Likewise, if I try to add your cassandra dashboard to this (apparently not working datasource), the metrics are empty. What is the correct datasource spec here/what am I missing? Are there additional installs/configs needed? 

I should note that I have only installed the exporter on *ONE* node for testing, but will install on all after testing on one node is successful. 

Thanks much in advance!

**Comment by geobeau** [comment]
I think you miss Prometheus somewhere. This exporter expose metrics for a Prometheus and then the datasource in grafana is the Prometheus.

**Comment by fhopp** [comment]
Thanks for the prompt response. 
The README of this repo did not mention anything of a Prometheus install (unless I messed it), but only stated to run the .jar file. I followed this [tutorial](https://www.robustperception.io/monitoring-cassandra-with-prometheus) to install prometheus, so perhaps you can help/clarify how to integrate the exporter with prometheus? 
Thanks much!

**Comment by geobeau** [comment]
I recommend that you try to find a Prometheus workshop to familiarise yourself with how it works (maybe https://github.com/mmedum/prometheus-workshop but I haven't tested it myself)

Edit the prometheus.yaml with this in your case, it should scrape metrics from `localhost:8082`: 
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:

scrape_configs:
  - job_name: 'cassandra-exporter'

    static_configs:
      - targets: ['localhost:8082']
```

then in Grafana, add a Prometheus datasource on localhost:9090 (or whatever port your prometheus is running on)

**Comment by fhopp** [comment]
Thanks very much, that resolved it.
--
Frederic R. Hopp (he/him/his)
PhD Candidate -- UCSB Department of Communication <https://comm.ucsb.edu/>
Researcher -- Media Neuroscience Lab <https://www.medianeuroscience.org/>
fhopp.github.io
