### ISSUE TITLE
Metrics still active after "DROP TABLE"

### ISSUE THREAD

**Issue by yakirgb** [criteo/cassandra_exporter#98]
Hi @erebe , great project,
I saw bug in cassandra_exporter, after delete of table, the exporter still show metrics of deleted table.
Very easy to reproduce:

1. Create table
2. Check metrics: ```[root@r1 ~]# curl -s localhost:8080/metrics  | grep foo  |wc -l
37```
3. Drop table
4. cassandra_exporter still show metrics of deleted table, until restart to cassandra_rxporter service: ```[root@r1 ~]# curl -s localhost:8080/metrics  | grep foo  |wc -l
37```
5. Restart cassandra_exporter: `systemctl restart cassandra_exporter.service`
6. And now the metrics looks fine: ```[root@r1 ~]# curl -s localhost:8080/metrics  | grep foo  |wc -l
0```

Thank you,
Yakir Gibraltar

**Comment by erebe** [comment]
Hello,

I am not part of Criteo (the org owning this repo) anymore, so I don't have more rights than you on this repository at this time : )
So I guess PR is welcome ^^

Regarding the issue, you are right. Once a metric is stored inside the Prometheus registry (the object that contains the metrics internally) is never cleand/diffed with what exist inside cassandra.
https://github.com/criteo/cassandra_exporter/blob/master/src/main/java/com/criteo/nosql/cassandra/exporter/JmxScraper.java#L49

To solve the issue, either we should erase the content of the registry from time ot time somewhere after 
https://github.com/criteo/cassandra_exporter/blob/master/src/main/java/com/criteo/nosql/cassandra/exporter/JmxScraper.java#L183

or try to accumulate new metrics in a temporary Prometheus register that we swap with the default one in the end of the run (should be a bit more rewrite)

**Comment by egoroof** [comment]
I also have issue with active metrics when they should gone, but with repair treadpool metrics - they stay alive even after repair is done.
![1](https://user-images.githubusercontent.com/2605831/109279396-46774000-784c-11eb-9da5-61d8efd99182.png)

```
cassandra_stats{cluster="Testing Tiles",datacenter="n3-staging",keyspace="",table="",name="org:apache:cassandra:metrics:threadpools:internal:repair#22:activetasks:value",} 1.0
```

After I restart the exporter its gone
![2](https://user-images.githubusercontent.com/2605831/109279587-84746400-784c-11eb-8a22-46b19bfe6e70.png)

exporter:2.3.5
cassandra:3.11.8
